[package]
name = "interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
bytecode = { workspace = true }
cranelift = "0.110.2"
cranelift-native = "0.110.2"
cranelift-jit = "0.110.2"
cranelift-module = "0.110.2"
